import Head from "next/head";
import Header from "./header";
import Footer from "./footer";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="site-content">
        <Header />
        <main>{children}</main>
        <Footer />
      </div>
    </>
  );
}
