import Head from 'next/head'
import Header from './header'
import Footer from './footer'

export default function Layout({ children }) {
    return (
        <>
            <Head>
                <title>RCAbney</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
                <link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&family=Raleway:wght@400;700&display=swap" rel="stylesheet" />
            </Head>
            <div className="site-content">
                <Header />
                <main>
                    {children}
                </main>
                <Footer />
            </div>
        </>
    )
}